version: '3'

services:
 db:
  image: mysql:5.7
  container_name: mysqlYml
  command: mysqld --character-set-server=utf8  --collation-server=utf8_general_ci
  restart: always
  ports:
   - '3306:3306'
  environment:
    MYSQL_USER: qy       
    MYSQL_PASSWORD: Ee123  
    MYSQL_ROOT_PASSWORD: Ee123
 web:
  build: .
  container_name: 'aspnetcore'
  ports:
    - "8003:80"
  depends_on:
    - db